### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rusty-snake** [ChimneySwift/multitools#3]
Hi, I use this mod downloaded from contentDB which is actually still at b082db11e467b182f95fa3a30231deaec75c6f7c. I found a crash which happens if `digger` is `nil` and indexed.

https://github.com/ChimneySwift/multitools/blob/b082db11e467b182f95fa3a30231deaec75c6f7c/init.lua#L221

I fixed that for now with adding `digger and`.

```diff
- if digger:get_wielded_item():get_name() ~= ("multitools:multitool_lava") then
+ if digger and digger:get_wielded_item():get_name() ~= ("multitools:multitool_lava") then
```

**Comment by ChimneySwift** [comment]
Should be fixed in 05501f1
